import os
import asyncio
from telegram.ext import Application, CommandHandler

TOKEN = os.getenv("TOKEN")

async def start(update, context):
    await update.message.reply_text("ðŸ¤– Bot Slots ativo!")

async def main():
    if not TOKEN:
        raise RuntimeError("TOKEN nÃ£o encontrado nos Secrets")

    application = Application.builder().token(TOKEN).build()
    application.add_handler(CommandHandler("start", start))

    print("Bot rodando...")
    await application.run_polling()

if __name__ == "__main__":
    asyncio.run(main())

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          python bot1.py


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          python bot1.py
